[package]
name = "practice-iced"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.10"
iced_aw = { version = "0.7.0", default-features = false,features = ["tab_bar", "tabs"] }